# Generated by Django 5.1.2 on 2025-11-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Unique identifier (e.g., 'signal-sentence', '3x3-message-builder')", max_length=200, unique=True)),
                ('summary', models.TextField(help_text='Brief summary of the concept (≤120 words)')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization and retrieval')),
                ('exercise_seeds', models.JSONField(blank=True, default=list, help_text='Example exercise prompts/templates')),
                ('citations', models.JSONField(blank=True, default=list, help_text="Source citations (e.g., [{'module': 'Module A - Foundations', 'section': 'Signal Sentence'}])")),
                ('module', models.CharField(choices=[('A', 'Module A - Foundations'), ('B', 'Module B - Audience'), ('C', 'Module C - Style'), ('D', 'Module D - Clarity')], help_text='Which Level-1 module this knowledge block belongs to', max_length=1)),
                ('content', models.TextField(help_text='Full content/explanation of the concept')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['module', 'slug'],
            },
        ),
        migrations.RenameField(
            model_name='level',
            old_name='gems_reward',
            new_name='tickets_reward',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='gems',
            new_name='tickets',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='gems_reward',
        ),
        migrations.AddField(
            model_name='district',
            name='ticket_cost_per_venue',
            field=models.IntegerField(default=1, help_text='Tickets required to enter each venue in this district'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='concept_refs',
            field=models.JSONField(blank=True, default=list, help_text='List of KnowledgeBlock slugs used'),
        ),
        migrations.AddField(
            model_name='level',
            name='unlock_rule',
            field=models.CharField(default='complete_previous_level', help_text="Rule for unlocking this level (e.g., 'must_pass_milestone', 'complete_modules_a_d')", max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='ab_variant',
            field=models.CharField(choices=[('A', 'Dashboard-first'), ('B', 'Map-first')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='contexts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='goals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='persona',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='quest',
            name='quest_type',
            field=models.CharField(choices=[('daily', 'Daily Quest')], default='daily', max_length=10),
        ),
    ]
